root_package: SampleDomain
model_package: Model
test_package: Test
source: ./sample_recipes/drawio/sample.xml
parser: drawio
dest_root: ./build/sample_drawio_java
templates_folder: ./mdg/templates
default_dialect: spring data rest
generation_artifacts:
# Java: JHipster
- dest: jdl{{package.path}}{{package.name | case_package}}.jdl
  level: package
  source: Java/entities.jdl.jinja
# Java: Spring Data Rest
- dest: java/entities{{cls.package.path}}{{cls.name | case_class}}.java
  level: class
  source: Java/pojos.java.jinja
- dest: java/enums{{enum.package.path}}{{enum.name | case_class}}.java
  level: enumeration
  source: Java/enums.java.jinja
# Documentation
- dest: base.txt
  level: root
  source: base.txt.jinja
test_templates:
- dest: ./build/sample_drawio_java/json{{ins.package.path}}/{{ins.stereotype}}.json
  format: json
