root_package: "{EE550A71-3A5F-473d-A3AF-773E900C74ED}"
model_package: "{D6D3BF36-E897-4a8b-8CA9-62ADAAD696ED}"
test_package: "{C2E30D48-F8AB-4c6f-9FA3-AFE44653D5EB}"
source: sqlite:///./sample_recipes/sparxdb/sample.qea
parser: sparxdb
dest_root: ./build/sample_sparxdb_graphql
templates_folder: ./mdg/templates
default_dialect: django
case_package: PascalCase
case_class: PascalCase
case_attribute: snake_case
generation_artifacts:
# Hasura Schema
- dest: "{{package.name | pascalcase}}-hasura_metadata.json"
  level: root
  source: "hasura.json.jinja"

# Django app
- dest: "{{package.root_package.name | pascalcase}}/{{package.name | pascalcase}}/models.py"
  level: package
  source: "django/app/models.py.jinja"
  filter: "{% if package.classes != [] %}True{% else %}False{% endif %}"
